BAR_CHART = "bar-chart"
SLIDER = "slider"
TOGGLE_SLIDER ="slider"
SELECT_ALL_TIMES_BUTTON = "select-all-times-button"
TIME_DROPDOWN = "time-dropdown"
START_RANGE_DROPDOWN = "start-range-dropdown"
END_RANGE_DROPDOWN = "end-range-dropdown"
CHOOSE_DATE_DROPDOWN = "start-range-dropdown"
LINE_CHART="line-chart"
CHOOSE_OPTION_DROPDOWN = "choose-option-dropdown"

SELECT_ALL_MONTHS_BUTTON = "select-all-months-button"
MONTH_DROPDOWN = "month-dropdown"

DAY_DROPDOWN = "day-dropdown"
SELECT_ALL_DAYS_BUTTON = "select-all-days-button"